version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    restart: unless-stopped
    networks:
      - app-network

  app1:
    image: dynamo28/rablo-assignment:v1.0
    container_name: rablo-app1
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - app-network

  app2:
    image: dynamo28/rablo-assignment:v1.0
    container_name: rablo-app2
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

